#!/usr/bin/env bash
# set -x
# Prevent repeated sourcing
if [ -n "${_MODULE_CHECK_OFFLINE_MEM_BLKS_}" ]; then
  return
fi
_MODULE_CHECK_OFFLINE_MEM_BLKS_="Loaded"

# Find 'CXL' devices in `lspci`
function cxl_offline_mem_blocks() {
  local FNAME=$1        # File name to process
  local ERR_STATE=""    # Used for error reporting
  local result=""	      # Used to handle the result from the grep command

  # Exit the function with a SKIPPED message if the file to process doesn't exist
  if [[ ! -f ${FNAME} ]] ; then
    rule_result SKIPPED "Could not process '${FNAME}'. File not found"
    return
  fi

  # Find 'CXL' in the `lspci` output
  res=$(${GREP} -E "^[0-9].*offline" ${FNAME})
  case "$?" in 
    0)
      rule_result FAILED "One or more memory blocks was found to be OFFLINE!"
      ;;
    1)
      rule_result PASSED "All memory blocks were ONLINE"
      ;;
    *)
      rule_result SKIPPED "Failed to process 'lsmem_-a_-o_RANGE,SIZE,STATE,REMOVABLE,ZONES,NODE,BLOCK' looking for 'OFFLINE' memory blocks!"
      ;;
  esac
}

# Call the main function
cxl_find_devices "${OUTPUT_PATH}/lsmem_-a_-o_RANGE,SIZE,STATE,REMOVABLE,ZONES,NODE,BLOCK"

set +x