#!/usr/bin/env bash
#set -x
# Prevent repeated sourcing
if [ -n "${_MODULE_CHECK_DIMM_VIRAL_STATE_}" ]; then
  return
fi
_MODULE_CHECK_DIMM_VIRAL_STATE_="Loaded"

# Validate ViralState == 0
function optane_check_dimm_viral_state() {
  local FNAME=$1        # File name to process
  local ERR_STATE=false # Used for error reporting

  # Exit the function with a SKIPPED message if the file to process doesn't exist
  if [[ ! -f ${FNAME} ]] ; then
    rule_result SKIPPED "Could not process '${FNAME}'. File not found"
    return
  fi

  while IFS='|' read -r DimmID Property Value 
  do
    DimmID="$(echo ${DimmID})"         # Remove leading and trailing whitespaces
    Property="$(echo ${Property})" # Remove leading and trailing whitespaces
    PropertyValue="$(echo ${Value})"   # Remove leading and trailing whitespaces
    if [ ${OPT_VERBOSITY} -ge 3 ]; then
      debug_msg "DimmID ${DimmID}: ${Property}=${Value}"
    fi
    # If viral policy != 0 report error
    if [[ "${PropertyValue}" -ne "0" ]]; then 
        ERR_STATE=true
    fi             
  done <<<  "$(${GREP} ViralState ${FNAME})" || return 0

  # Return the final PASS/FAIL to the user
  if [ "${ERR_STATE}" = true ] ; then
    rule_result FAILED "One or more PMem modules have ViralState != 0"
  else
    rule_result PASSED "All PMem modules are not ViralState == 0"
  fi
}

# Call the main function
optane_check_dimm_viral_state "${OUTPUT_PATH}/ipmctl_show_-a_-dimm.psv"
