#!/usr/bin/env bash
#set -x

# Prevent repeated sourcing
if [ -n "${__MODULE_CHECK_DIMM_FW_UPDATE_STATUS_}" ]; then
  return
fi
__MODULE_CHECK_DIMM_FW_UPDATE_STATUS__="Loaded"

# Validate FW Update Status  == N/A
function optane_check_dimm_fwupdatestatus() {
  local FNAME=$1        # File name to process
  local ERR_STATE=false # Used for error reporting

  # Exit the function with INFO message if the file to process doesn't exist
  if [[ ! -f ${FNAME} ]] ; then
    info_msg " Could not process '${FNAME}'. File not found"
    REPORT_COUNT_INFO=$((REPORT_COUNT_INFO+1)) # Increment the INFO count
    return
  fi

  # Create Associative Array
  declare -A FW_Version  # Key is the DIMM Property value; Value is a list of DIMMs with this Property value

  # Get the DimmID, Property, and Value fields from the input file
  while IFS='|' read -r DimmID Property Value 
  do
    DimmID="$(echo ${DimmID})"         # Remove leading and trailing whitespaces
    Property="$(echo ${Property})" # Remove leading and trailing whitespaces
    PropertyValue="$(echo ${Value})"   # Remove leading and trailing whitespaces
    if [ ${OPT_VERBOSITY} -ge 3 ]; then
      debug_msg "DimmID ${DimmID}: ${Property}=${Value}"
    fi
    # Report PMem Modules that have FW Update Status != N/A 
    if [[ "$PropertyValue" != "N/A" ]]; then
      ERR_STATE=true
    fi
    # Add the DIMM to the associative array 
   FW_Version[${PropertyValue}]+="${DimmID},"
  done <<<  "$(${GREP} StagedFWVersion ${FNAME})" || return 0 

  # Report DIMMS with staged firmware
  if [ "${ERR_STATE}" = true ]; then
    info_msg "Multiple (${#FW_Version[@]}) ${Property} DIMM states found!"
    for d in "${!FW_Version[@]}" ; do # Display the full list of DIMMs found
      FW_Version=${FW_Version[${d}]::-1} # Strip the last character ',' from the string
      info_msg "${d} = ${FW_Version}"
    done
  fi

  # Return the final PASS/FAIL to the user
  if [ "${ERR_STATE}" = true ] ; then
    echo "${STR_FAIL} ${FUNCNAME[0]} : One or more PMem modules have a staged Firmware Update" 
    REPORT_COUNT_FAILED=$((REPORT_COUNT_FAILED+1))
  else
    echo "${STR_PASSED} ${FUNCNAME[0]} : All PMem modules have no staged Firmware Update" 
    REPORT_COUNT_PASSED=$((REPORT_COUNT_PASSED+1))
  fi
}

# Call the main function
optane_check_dimm_fwupdatestatus "${OUTPUT_PATH}/ipmctl_show_-a_-firmware.psv"
