#!/usr/bin/env bash
#set -x
# Prevent repeated sourcing
if [ -n "${_MODULE_CHECK_DIMM_EXTENDED_ADR_ENABLED_}" ]; then
  return
fi
_MODULE_CHECK_DIMM_EXTENDED_ADR_ENABLED_="Loaded"

# Validate ExtendedAdrEnabled == 0 or 1
function optane_check_dimm_extended_adr_enabled() {
  local FNAME=$1        # File name to process
  local ERR_STATE=false # Used for error reporting

  # Exit the function with INFO message if the file to process doesn't exist
  if [[ ! -f ${FNAME} ]] ; then
    rule_result SKIPPED "Could not process '${FNAME}'. File not found"
    return
  fi

  # Get the DimmID, Property, and Value fields from the input file
  while IFS='|' read -r DimmID Property Value 
  do
    DimmID="$(echo ${DimmID})"         # Remove leading and trailing whitespaces
    Property="$(echo ${Property})" # Remove leading and trailing whitespaces
    PropertyValue="$(echo ${Value})"   # Remove leading and trailing whitespaces
    if [ ${OPT_VERBOSITY} -ge 3 ]; then
      debug_msg "DimmID ${DimmID}: ${Property}=${Value}"
    fi
    # If ExtendedAdrEnabled != 0 report as info   
    if [[ "${PropertyValue}" -ne "0" ]]; then   
        ERR_STATE=true 
    fi             
  done <<<  "$(${GREP} -E ExtendedAdrEnabled ${FNAME})" || return 0

  # Return the final PASS/FAIL to the user
  if [ "${ERR_STATE}" = true ] ; then
    rule_result FAILED "One or more PMem modules have ExtendedAdrEnabled switch Enabled"
  else
    rule_result PASSED "All PMem modules have ExtendedAdrEnabled switch disabled"
  fi
}

# Call the main function
optane_check_dimm_extended_adr_enabled "${OUTPUT_PATH}/ipmctl_show_-a_-dimm.psv"
