#!/usr/bin/env bash
#set -x

# Prevent repeated sourcing
if [ -n "${_MODULE_CHECK_FW_ERROR_COUNT_}" ]; then
  return
fi
_MODULE_CHECK_FW_ERROR_COUNT_="Loaded"

# check Firmware Error Count
function optane_dimm_check_fw_error_count() {
  local FNAME=$1        # File name to process
  local ERR_STATE=false # Used for error reporting

  # Exit the function with INFO message if the file to process doesn't exist
  if [[ ! -f ${FNAME} ]] ; then
    info_msg " Could not process '${FNAME}'. File not found"
    REPORT_COUNT_INFO=$((REPORT_COUNT_INFO+1)) # Increment the INFO count
    return
  fi

  # Get the DimmID and Current Value(FWError Count) fields from the input file
  while IFS='|' read -r DimmID Type CurrentValue
  do
    DimmID="$(echo ${DimmID})"
    CurrentValue=(${CurrentValue})

    # Check the FWError Count
    if [[ ${CurrentValue} -lt 49 ]] && [[ ${CurrentValue} -ge 10 ]]
    then
      REPORT_COUNT_INFO=$((REPORT_COUNT_INFO+1))
      info_msg "DimmID ${DimmID} has ${CurrentValue} FwError Count"
    elif [[ ${CurrentValue} -lt 100 ]] && [[ ${CurrentValue} -ge 50 ]]
    then
      REPORT_COUNT_WARNINGS=$((REPORT_COUNT_WARNINGS+1))
      warn_msg "DimmID ${DimmID} has ${CurrentValue} FwError Count"
      ERR_STATE=true
    elif [[ ${CurrentValue} -ge 100 ]]
    then
      REPORT_COUNT_CRITICAL=$((REPORT_COUNT_CRITICAL+1))
      crit_msg "DimmID ${DimmID} has ${CurrentValue} FwError Count"
      ERR_STATE=true
    fi
  done <<<  "$(${GREP} FwErrorCount ${FNAME})" || return 0

  # Return the final PASS/FAIL to the user
  if [ "${ERR_STATE}" = true ] ; then
    echo "${STR_FAIL} ${FUNCNAME[0]} : One or more PMem Modules reported having  50 or more FWError Count."
    REPORT_COUNT_FAILED=$((REPORT_COUNT_FAILED+1))
  else
    echo "${STR_PASSED} ${FUNCNAME[0]} : All PMem Modules have less than 10 FWError Counts "
    REPORT_COUNT_PASSED=$((REPORT_COUNT_PASSED+1))
  fi
}

# Call the main function
optane_dimm_check_fw_error_count "${OUTPUT_PATH}/ipmctl_show_-sensor"
