#!/usr/bin/env bash
#set -x

# Prevent repeated sourcing
if [ -n "${__MODULE_CHECK_REGION_CAPACITY__}" ]; then
  return
fi
__MODULE_CHECK_REGION_CAPACITY__="Loaded"

# Validate all regions have the same capacity 
function optane_check_region_capacity() {
  local FNAME=$1        # File name to process
  local ERR_STATE=false # Used for error reporting

  # Exit the function with INFO message if the file to process doesn't exist
  if [[ ! -f ${FNAME} ]] ; then
    rule_result SKIPPED "Could not process '${FNAME}'. File not found"
    return
  fi

  # Create Associative Arrays
  declare -A REGION_CAPACITY    # Key is the Capacity; Value is a list of Regions with this Capacity

  # Get the SocketID and Capacity fields from the input file
  while IFS='|' read -r SocketID ISetID PersistentMemoryType Capacity FreeCapacity HealthState
  do
    SocketID="$(echo ${SocketID})"      # Remove leading and trailing whitespaces
    Capacity="$(echo ${Capacity})"      # Remove leading and trailing whitespaces
    if [ ${OPT_VERBOSITY} -ge 3 ]; then
      debug_msg "Socket Capacity: ${SocketID}=${Capacity}"
    fi
    # Add the Region Capacity to the array 
    REGION_CAPACITY[${Capacity}]+="${SocketID},"
  done <<<  "$(tail -n +3 ${FNAME})" # Skip the header lines (1&2), and start reading from line 3

  # Report Regions with different capacities
  if [[ ${#REGION_CAPACITY[@]} -gt 1 ]]; then
    info_msg "Multiple (${#REGION_CAPACITY[@]}) Regions have different capacities!" 2
    for r in "${!REGION_CAPACITY[@]}" ; do # Display the full list of Regions found
      REGION_LIST=${REGION_CAPACITY[${r}]::-1} # Strip the last character ',' from the string
      info_msg "Region ${REGION_LIST} = ${r}" 2
    done
    ERR_STATE=true
  fi

  # Return the final PASS/FAIL to the user
  if [ "${ERR_STATE}" = true ] ; then
    rule_result FAILED "One or more regions have different capacities. See previous errors."
  else
    rule_result PASSED "All Regions have the same Capacity"
  fi
}

# Call the main function
optane_check_region_capacity "${OUTPUT_PATH}/ipmctl_show_-region"
