#!/usr/bin/env bash
#set -x

# Prevent repeated sourcing
if [ -n "${__MODULE_CHECK_DIMM_RESERVEDCAPACITY__}" ]; then
  return
fi
__MODULE_CHECK_DIMM_RESERVEDCAPACITY__="Loaded"

# Report an INFO message if the system has reserved capacity
function optane_check_dimm_reservedcapacity() {
  local FNAME=$1        # File name to process
  local ERR_STATE=false # Used for error reporting

  # Exit the function with INFO message if the file to process doesn't exist
  if [[ ! -f ${FNAME} ]] ; then
    info_msg " Could not process '${FNAME}'. File not found"
    REPORT_COUNT_INFO=$((REPORT_COUNT_INFO+1)) # Increment the INFO count
    return
  fi

  # Create Associative Arrays
  declare -A DIMM_HEALTH    # Key is the ReservedCapacity value; Value is a list of PMem Modules with this ReservedCapacity value

  # Get the SocketID and FreeCapacity fields from the input file
  while IFS='|' read -r DimmID Property Value
  do
    DimmID="$(echo ${DimmID})"         # Remove leading and trailing whitespaces
    PropertyType="$(echo ${Property})" # Remove leading and trailing whitespace
    PropertyValue="$(echo ${Value})"   # Remove leading and trailing whitespaces
    if [ ${OPT_VERBOSITY} -ge 3 ]; then
      debug_msg "DimmID ${DimmID}: ${Property}=${Value}"
    fi
    # Report PMem Modules that have ReservedCapacity > 0GiB
    if [[ "${PropertyValue}" != "0.000 GiB" ]]; then
      ERR_STATE=true
    fi
    # Add the DIMM to the associative array
    DIMM_HEALTH[${PropertyValue}]+="${DimmID},"
  done <<<  "$(${GREP} ReservedCapacity ${FNAME})" || return 0

  # Report non-Healthy DIMMs
  if [ "${ERR_STATE}" = true ]; then
    info_msg "Multiple (${#DIMM_HEALTH[@]}) ${PropertyType} DIMM states found!" 2
    for d in "${!DIMM_HEALTH[@]}" ; do # Display the full list of DIMMs found
      DIMM_LIST=${DIMM_HEALTH[${d}]::-1} # Strip the last character ',' from the string
      info_msg "${d} = ${DIMM_LIST}" 2
    done
  fi

  # Return the final PASS/INFO to the user
  if [ "${ERR_STATE}" = true ] ; then
    echo "${STR_INFO} ${FUNCNAME[0]} : One or more PMem modules reported > 0.000 GiB ReservedCapacity" 
    REPORT_COUNT_INFO=$((REPORT_COUNT_INFO+1))
  else
    echo "${STR_PASSED} ${FUNCNAME[0]} : No PMem modules have ReservedCapacity configured" 
    REPORT_COUNT_PASSED=$((REPORT_COUNT_PASSED+1))
  fi
}

# Call the main function
optane_check_dimm_reservedcapacity "${OUTPUT_PATH}/ipmctl_show_-a_-dimm.psv"
