#!/usr/bin/env bash
#set -x

# Prevent repeated sourcing
if [ -n "${_MODULE_CHECK_DIMM_MIXEDSKU_}" ]; then
  return
fi
_MODULE_CHECK_DIMM_MIXEDSKU_="Loaded"

# Validate DIMM MixedSKU !- 0
function optane_check_mixed_sku() {
  local FNAME=$1        # File name to process
  local ERR_STATE=false # Used for error reporting

  # Exit the function with INFO message if the file to process doesn't exist
  if [[ ! -f ${FNAME} ]] ; then
    info_msg " Could not process '${FNAME}'. File not found"
    REPORT_COUNT_INFO=$((REPORT_COUNT_INFO+1)) # Increment the INFO count
    return
  fi

  # Create Associative Array
  declare -A MixedSKU  # Key is the DIMM Property value; Value is a list of DIMMs with this Property value

  # Get the DimmID, Property, and Value fields from the input file
  while IFS='|' read -r DimmID Property Value 
  do
    DimmID="$(echo ${DimmID})"         # Remove leading and trailing whitespaces
    Property="$(echo ${Property})" # Remove leading and trailing whitespaces
    PropertyValue="$(echo ${Value})"   # Remove leading and trailing whitespaces
    if [ ${OPT_VERBOSITY} -ge 3 ]; then
      debug_msg "DimmID ${DimmID}: ${Property}=${Value}"
    fi
    # Report PMem Modules that have PackageSparingCapable  = 0 (False/Disabled) 
    if [[ "${PropertyValue}" -ne 0 ]]; then
      ERR_STATE=true
    fi
    # Add the DIMM to the associative array 
   MixedSKU[${PropertyValue}]+="${DimmID},"
  done <<<  "$(${GREP} MixedSKU ${FNAME})" || return 0

  # Report DIMMS with MixedSKU value greater than 0
  if [ "${ERR_STATE}" = true ]; then
    info_msg "Multiple (${#MixedSKU[@]}) ${Property} DIMM states found!"
    for d in "${!MixedSKU[@]}" ; do # Display the full list of DIMMs found
      MixedSKU=${MixedSKU[${d}]::-1} # Strip the last character ',' from the string
      info_msg "${d} = ${MixedSKU}"
    done
  fi

  # Return the final PASS/FAIL to the user
  if [ "${ERR_STATE}" = true ] ; then
    echo "${STR_FAIL} ${FUNCNAME[0]} : One or more PMem modules reported MixedSKU Value != 0" 
    REPORT_COUNT_FAILED=$((REPORT_COUNT_FAILED+1))
  else
    echo "${STR_PASSED} ${FUNCNAME[0]} : All PMem modules have a MixedSKU Value of 0" 
    REPORT_COUNT_PASSED=$((REPORT_COUNT_PASSED+1))
  fi
}

# Call the main function
optane_check_mixed_sku "${OUTPUT_PATH}/ipmctl_show_-a_-dimm.psv"
