#!/usr/bin/env bash
#set -x
# Prevent repeated sourcing
if [ -n "${_MODULE_CHECK_DIMM_PPC_EXTENDED_ADR_ENABLED_}" ]; then
  return
fi
_MODULE_CHECK_DIMM_PPC_EXTENDED_ADR_ENABLED_="Loaded"

# Validate PpcExtendedAdrEnabled == 1
function optane_check_dimm_ppc_extended_adr_enabled() {
  local FNAME=$1        # File name to process
  local ERR_STATE=false # Used for error reporting
  # Exit the function with INFO message if the file to process doesn't exist
  if [[ ! -f ${FNAME} ]] ; then
    info_msg " Could not process '${FNAME}'. File not found"
    REPORT_COUNT_INFO=$((REPORT_COUNT_INFO+1)) # Increment the INFO count
    return
  fi
  # Create Associative Array
  # Get the DimmID, Property, and Value fields from the input file
  while IFS='|' read -r DimmID Property Value 
  do
    DimmID="$(echo ${DimmID})"         # Remove leading and trailing whitespaces
    Property="$(echo ${Property})"     # Remove leading and trailing whitespaces
    PropertyValue="$(echo ${Value})"   # Remove leading and trailing whitespaces
    if [ ${OPT_VERBOSITY} -ge 3 ]; then
      debug_msg "DimmID ${DimmID}: ${Property}=${Value}"
    fi
    # If PpcExtendedAdrEnabled != 1 report Err and report the detials    
    if [[ "${PropertyValue}" -ne "1" ]]; then   
        ERR_STATE=true
    fi             
  done <<<  "$(${GREP} -E PpcExtendedAdrEnabled ${FNAME})" || return 0
  # Return the final PASS/FAIL to the user
  if [ "${ERR_STATE}" = true ] ; then
    info_msg "One or more PMem modules have PpcExtendedAdrEnabled=False (Disabled)" 
    REPORT_COUNT_INFO=$((REPORT_COUNT_INFO+1))
   else
     info_msg "All PMem modules have PpcExtendedAdrEnabled=True (Enabled)" 
     REPORT_COUNT_INFO=$((REPORT_COUNT_INFO+1))
  fi
}
# Call the main function
optane_check_dimm_ppc_extended_adr_enabled "${OUTPUT_PATH}/ipmctl_show_-a_-dimm.psv"
