#!/usr/bin/env bash
#set -x

# Define the message type printing formats

_HDR_FMT="%s %s "
_MSG_FMT="${_HDR_FMT} : %s\n"

# Print INFO messages with the function name and optional string message
function info_msg() {
  echo "${STR_INFO} ${FUNCNAME[1]} : ${@}"
}

function warn_msg() {
  echo "${STR_WARN} ${FUNCNAME[1]} : ${@}"
}

function crit_msg() {
  echo "${STR_CRIT} ${FUNCNAME[1]} : ${@}"
}

